---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: Create vcn
      oci_network_vcn:
        cidr_block: "10.0.0.0/16"
        compartment_id: "ocid1.compartment.oc1..aaaaaaaahkhvj2skdw3ty7fnhg6jop5tr5ie3muwbcmlhsy426zxamtajpgq"
        display_name: "TESTVCN"
        defined_tags: {'mylab': {'environment':'LAB'}}