---
- name : List summary of existing buckets in OCI object storage
  collections:
    - oracle.oci
  connection: local
  hosts: localhost
  tasks:
    - name: Create vcn
      oci_network_vcn:
        vcn_id: "ocid1.vcn.oc1.eu-zurich-1.amaaaaaamvhaknqa5i4j5i73vrcys4zkxlqqm6uwu7mbvr7x7xkked5awglq"
        state: absent