---
# tasks file for httpd
  - import_tasks: rocky_install.yml
    when:
      ansible_facts['os_family']|lower == 'rocky'

  - import_tasks: redhat_install.yml
    when:
      ansible_facts['os_family']|lower == 'redhat'

  - import_tasks: debian_install.yml
    when:
      ansible_facts['os_family']|lower == 'debian'

  - import_tasks: rocky_configure.yml
    when:
      ansible_facts['os_family']|lower == 'rocky'

  - import_tasks: redhat_configure.yml
    when:
      ansible_facts['os_family']|lower == 'redhat'

  - import_tasks: debian_configure.yml
    when:
      ansible_facts['os_family']|lower == 'debian'

  - import_tasks: rocky_service.yml
    when:
      ansible_facts['os_family']|lower == 'rocky'
  
  - import_tasks: redhat_service.yml
    when:
      ansible_facts['os_family']|lower == 'redhat'

  - import_tasks: debian_service.yml
    when:
      ansible_facts['os_family']|lower == 'debian'

  - import_tasks: rocky_template.yml
    when:
      ansible_facts['os_family']|lower == 'rocky'

  - import_tasks: redhat_template.yml
    when:
      ansible_facts['os_family']|lower == 'redhat'

  - import_tasks: debian_template.yml
    when:
      ansible_facts['os_family']|lower == 'debian'